<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>RulealizeStudio.Sample.Countdown</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <AdditionalFiles Include="countdown.json" />
  </ItemGroup>

  <!-- What countdown.json requires. -->
  <ItemGroup>
    <PackageReference Include="Rulealize.Plugin.TypeSchema" Version="1.2.0" />
    <PackageReference Include="Rulealize.Plugin.State" Version="1.0.1" />
    <PackageReference Include="Rulealize.Plugin.Comparison" Version="1.0.1" />
    <PackageReference Include="Rulealize.Plugin.Arithmetic" Version="1.0.1" />
    <PackageReference Include="Rulealize.Plugin.Sequence" Version="1.4.0" />
    <PackageReference Include="Rulealize.Plugin.Binding" Version="1.0.1" />
  </ItemGroup>

</Project>
